### ISSUE TITLE
Nič se ne dogaja

### ISSUE THREAD

**Issue by matijapretnar** [timotejvesel/Blackjack#1]
Ker bodo v kratkem kratke predstavitve, čimprej začnite z delom na projektu. Na spletni učilnici sem [objavil navodila](https://ucilnica.fmf.uni-lj.si/mod/forum/discuss.php?d=15136), kako začeti.

**Comment by timotejvesel** [comment]
Do sedaj sem s simulacijami dobil optimalne strategije za igro in z njihovo pomočjo izračunal house edge. S tem sem verjetno ta del bolj kot ne končal (verjetno bi se dalo še optimizirati kodo; poleg tega bom, če bo dovolj časa, igor še izboljšal z nekaj novimi pravili).

Nisem pa prepričan kaj bi bilo smiselno narediti v Shinyu. Razmišljal sem, da bi uporabniku omogočil, da igra Blackjack (poleg tega pa bi mu program na vsakem koraku izpisal še kaj je optimalna poteza, ki jo lahko naredi). Ali bi bilo to primerno ter izvedljivo?

**Comment by timotejvesel** [comment]
Sem šele sedaj prebral v "navodilih", da bi vas moral označiti: @matijapretnar

**Comment by matijapretnar** [comment]
Po mojem bi bilo smiselno v Shinyju uporabniku namesto igranja omogočiti prikaz povezave med strategijami, številom poskusov in verjetnostjo zmage. Npr. ena možnost je, da uporabnik spreminja število poskusov, nato pa se mu nariše graf verjetnosti zmage (oz. morda tudi tega, koliko je bila razlika poraženca) v odvisnosti od strategije? Ampak vsekakor je dovolj narejenega, da tale issue zaprem.
