### ISSUE TITLE
Podvajanje kode

### ISSUE THREAD

**Issue by matijapretnar** [timotejvesel/Blackjack#2]
V vsaki strategiji se na začetku pojavi funkcija `vsota_karte`, ki je povsod enaka. To (in vse podobne funkcije) bi bilo treba definirati samo enkrat. Če se funkcije malo razlikujejo, pa bi bilo morda bolje uporabiti dodaten parameter.

**Comment by timotejvesel** [comment]
@matijapretnar 
Mislim, da mi je funkcije sedaj uspelo popraviti tako, da praktično ni več podvajanja.

**Comment by matijapretnar** [comment]
Kot gledam, je podvajanja še nekaj:
- datoteke `double-hard.r`, `double-soft.r`, `hit-stand-hard.r` ter `hit-stand-soft.r` imajo še vedno precej skupne kode, npr. prvi dve sta od vrstice `for(j in vrstice) {` do zadnjega zavitega oklepaja enaki, razen da ena uporabi `"hard"`, ena `"soft"`, pa da izpisujeta na različen način (čeprav to ni potrebno).
- v `str_igralec.r` imata funkciji `igra.d` in `igra.hs` prav tako precej skupnih vrstic
- podobno bi se verjetno dalo poenostaviti funkciji `igralec_str_d` ter `igralec_str_hs`, vendar je to malo težje videti. Najprej bi bilo treba obe spraviti na isto obliko, da sta veji `hard` in `soft` v različnem vrstnem redu ter da se skupni del v `igralec_str_d` da za `if/else` tako kot v `igralec_str_hs`.

**Comment by timotejvesel** [comment]
Sem popravil: 
* podvojeno kodo iz vseh štirih datotek sem združil v funkcijo `osnovna` v datoteki `osnovna-sim.r`,
 * funkciji sem združil v funkcijo `igra`,
 * funkciji sem združil v funkcijo `igralec_str`. Mislim, da deluje pravilno (sem jo tudi preizkusil in dobim ustrezne vrednosti v tabelah).

**Comment by matijapretnar** [comment]
Ok, super.
